services:
  db:
    container_name: ipinfo-postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_DB=ipInfoDb

  webapp:
    container_name: ipinfo-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5082:8080"
    depends_on:
      - "db"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  
  cache:
    container_name: ipinfo-redis
    image: redis
    ports:
      - "6379:6379"

    
    